# Generated by Django 3.1.4 on 2020-12-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('song', models.CharField(max_length=50, verbose_name='song')),
                ('position', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
    ]
