# Generated by Django 3.1.4 on 2020-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='song',
            field=models.CharField(max_length=100, verbose_name='song'),
        ),
    ]
